name: Node.js CI/CD with SonarQube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"] # Latest LTS version of Node.js

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

  backend-test:
    runs-on: ubuntu-latest

    needs: setup-node

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./backend

  sonarqube-scan:
    runs-on: ubuntu-latest

    needs: backend-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: -X

  # Deployment step will go here once you have secrets set up
