name: Node.js CI/CD with SonarQube, Cypress E2E, and Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"] # Choose the appropriate Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

  start-backend-frontend:
    runs-on: ubuntu-latest

    needs: setup-node

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./client

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Start Backend
        run: npm start
        working-directory: ./backend

      - name: Start Frontend
        run: npm run dev
        working-directory: ./client

  cypress-e2e:
    runs-on: ubuntu-latest

    needs: start-backend-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cypress Dependencies
        run: npm ci
        working-directory: ./client

      - name: Run Cypress E2E Tests
        run: npm run test
        working-directory: ./client

  sonarqube-scan:
    runs-on: ubuntu-latest

    needs: cypress-e2e

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: -X

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    needs: sonarqube-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t bassmit123/backend-server:latest ./backend

      - name: Push Backend Docker Image to Docker Hub
        run: docker push bassmit123/backend-server:latest

      - name: Build Client Docker Image
        run: docker build -t bassmit123/client:latest ./client

      - name: Push Client Docker Image to Docker Hub
        run: docker push bassmit123/client:latest
