name: Node.js CI/CD with SonarQube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"] # Latest LTS version of Node.js

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./backend

  sonarqube:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
      - name: Download SonarQube Scanner
        run: curl -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip && unzip sonar-scanner-cli-4.6.0.2311-linux.zip

      - name: Run SonarQube Scan
        run: |
          ./sonar-scanner-4.6.0.2311-linux/bin/sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization_key \
            -Dsonar.sources=./backend \
            -Dsonar.host.url=https://your-sonarqube-instance.com \
            -Dsonar.login=$SONARQUBE_TOKEN

# Deployment step will go here once you have secrets set up
