name: Node.js CI/CD with SonarQube and Cypress E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"] # Choose the appropriate Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

  backend-test:
    runs-on: ubuntu-latest

    needs: setup-node

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./backend

  start-backend-frontend:
    runs-on: ubuntu-latest

    needs: backend-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./client

      - name: Start Backend and Frontend
        run: |
          npm start & # Start your backend server
          (cd client && npm start) & # Start your frontend server
          wait

  cypress-e2e:
    runs-on: ubuntu-latest

    needs: start-backend-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cypress Dependencies
        run: npm ci
        working-directory: ./client

      - name: Run Cypress E2E Tests
        run: npm run cypress:run
        working-directory: ./client

  sonarqube-scan:
    runs-on: ubuntu-latest

    needs: cypress-e2e

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: -X

  # Deployment step will go here once you have secrets set up
